CREATE TABLE public.site_announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  href text,
  href_label text,
  style text NOT NULL DEFAULT 'ribbon',
  accent text NOT NULL DEFAULT '#e11d48',
  urgent boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  starts_at timestamptz,
  ends_at timestamptz,
  sort integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.site_announcements TO anon;
GRANT SELECT ON public.site_announcements TO authenticated;
GRANT ALL ON public.site_announcements TO service_role;
ALTER TABLE public.site_announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view announcements" ON public.site_announcements FOR SELECT USING (true);
CREATE POLICY "Admins manage announcements" ON public.site_announcements FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER site_announcements_touch BEFORE UPDATE ON public.site_announcements
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE public.courses
  ADD COLUMN IF NOT EXISTS badge text,
  ADD COLUMN IF NOT EXISTS badge_color text,
  ADD COLUMN IF NOT EXISTS badge_expires_at timestamptz;

ALTER TABLE public.committee_resources ADD COLUMN IF NOT EXISTS is_protected boolean NOT NULL DEFAULT true;

CREATE TABLE public.support_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'other',
  subject text NOT NULL DEFAULT '',
  message text NOT NULL,
  status text NOT NULL DEFAULT 'new',
  admin_notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT INSERT ON public.support_requests TO anon, authenticated;
GRANT SELECT, UPDATE, DELETE ON public.support_requests TO authenticated;
GRANT ALL ON public.support_requests TO service_role;
ALTER TABLE public.support_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can send a support request"
  ON public.support_requests FOR INSERT TO anon, authenticated
  WITH CHECK (
    length(message) BETWEEN 1 AND 4000
    AND length(subject) <= 200
    AND length(name) <= 120
    AND length(email) <= 200
    AND length(category) <= 40
    AND admin_notes = ''
    AND status = 'new'
    AND (user_id IS NULL OR user_id = auth.uid())
  );
CREATE POLICY "Admins can read support requests" ON public.support_requests FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can update support requests" ON public.support_requests FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "Admins can delete support requests" ON public.support_requests FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER support_requests_touch BEFORE UPDATE ON public.support_requests
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE INDEX support_requests_created_idx ON public.support_requests (created_at DESC);

CREATE TABLE public.support_channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL DEFAULT 'link',
  icon text NOT NULL DEFAULT 'link',
  label_en text NOT NULL DEFAULT '',
  label_ar text NOT NULL DEFAULT '',
  value text NOT NULL DEFAULT '',
  href text NOT NULL DEFAULT '',
  visible boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.support_channels TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.support_channels TO authenticated;
GRANT ALL ON public.support_channels TO service_role;
ALTER TABLE public.support_channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view support channels" ON public.support_channels FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage support channels" ON public.support_channels FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER support_channels_touch BEFORE UPDATE ON public.support_channels
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TABLE public.support_settings (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  page_enabled boolean NOT NULL DEFAULT true,
  form_enabled boolean NOT NULL DEFAULT true,
  channels_enabled boolean NOT NULL DEFAULT true,
  intro_title_en text NOT NULL DEFAULT 'Need a hand?',
  intro_title_ar text NOT NULL DEFAULT 'تحتاج مساعدة؟',
  intro_text_en text NOT NULL DEFAULT 'Tell us what is going on and our team will get back to you.',
  intro_text_ar text NOT NULL DEFAULT 'أخبرنا بما يحدث وسيتواصل معك فريقنا.',
  response_note_en text NOT NULL DEFAULT 'We usually reply within 24 hours.',
  response_note_ar text NOT NULL DEFAULT 'نرد عادة خلال 24 ساعة.',
  categories jsonb NOT NULL DEFAULT '[{"key":"payment","en":"Payment","ar":"الدفع"},{"key":"access","en":"Course access","ar":"الوصول للدورات"},{"key":"technical","en":"Technical","ar":"مشكلة تقنية"},{"key":"other","en":"Other","ar":"أخرى"}]'::jsonb,
  notify_enabled boolean NOT NULL DEFAULT false,
  notify_email text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.support_settings TO anon, authenticated;
GRANT INSERT, UPDATE ON public.support_settings TO authenticated;
GRANT ALL ON public.support_settings TO service_role;
ALTER TABLE public.support_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view support settings" ON public.support_settings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage support settings" ON public.support_settings FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER support_settings_touch BEFORE UPDATE ON public.support_settings
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
INSERT INTO public.support_settings (id) VALUES (true);

CREATE TABLE public.about_blocks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL DEFAULT 'story',
  title_en text NOT NULL DEFAULT '',
  title_ar text NOT NULL DEFAULT '',
  body_en text NOT NULL DEFAULT '',
  body_ar text NOT NULL DEFAULT '',
  image_url text NOT NULL DEFAULT '',
  link_url text NOT NULL DEFAULT '',
  extra jsonb NOT NULL DEFAULT '{}'::jsonb,
  visible boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.about_blocks TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.about_blocks TO authenticated;
GRANT ALL ON public.about_blocks TO service_role;
ALTER TABLE public.about_blocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view about blocks" ON public.about_blocks FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage about blocks" ON public.about_blocks FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER about_blocks_touch BEFORE UPDATE ON public.about_blocks
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
INSERT INTO public.about_blocks (kind, title_en, title_ar, body_en, body_ar, sort_order) VALUES
  ('hero', 'About us', 'من نحن', 'Medical study, made clear.', 'دراسة الطب، بوضوح.', 0),
  ('story', 'Our story', 'قصتنا', 'We started as a small group of medical students who wanted a better way to study — organised question banks, real resources, and no wasted time.', 'بدأنا كمجموعة صغيرة من طلاب الطب أرادوا طريقة أفضل للدراسة — بنوك أسئلة منظمة، ومصادر حقيقية، ودون إضاعة للوقت.', 1),
  ('stats', 'By the numbers', 'بالأرقام', '', '', 2),
  ('cta', 'Ready to start?', 'جاهز للبدء؟', 'Browse the courses and pick up where you left off.', 'تصفح الدورات وأكمل من حيث توقفت.', 3);

CREATE TABLE public.user_groups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  color text NOT NULL DEFAULT '#e11d48',
  kind text NOT NULL DEFAULT 'manual',
  course_id uuid REFERENCES public.courses(id) ON DELETE CASCADE,
  package_id uuid REFERENCES public.packages(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_groups TO authenticated;
GRANT ALL ON public.user_groups TO service_role;
ALTER TABLE public.user_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage user groups" ON public.user_groups FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE TRIGGER user_groups_touch BEFORE UPDATE ON public.user_groups
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TABLE public.user_group_members (
  group_id uuid NOT NULL REFERENCES public.user_groups(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_group_members TO authenticated;
GRANT ALL ON public.user_group_members TO service_role;
ALTER TABLE public.user_group_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage group members" ON public.user_group_members FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));

CREATE TABLE public.announcement_audiences (
  announcement_id uuid NOT NULL REFERENCES public.site_announcements(id) ON DELETE CASCADE,
  group_id uuid NOT NULL REFERENCES public.user_groups(id) ON DELETE CASCADE,
  PRIMARY KEY (announcement_id, group_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.announcement_audiences TO authenticated;
GRANT ALL ON public.announcement_audiences TO service_role;
ALTER TABLE public.announcement_audiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage announcement audiences" ON public.announcement_audiences FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));

CREATE OR REPLACE FUNCTION public.user_in_group(_user_id uuid, _group_id uuid)
RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE g public.user_groups;
BEGIN
  IF _user_id IS NULL THEN RETURN false; END IF;
  SELECT * INTO g FROM public.user_groups WHERE id = _group_id;
  IF NOT FOUND THEN RETURN false; END IF;
  IF EXISTS (SELECT 1 FROM public.user_group_members m
             WHERE m.group_id = _group_id AND m.user_id = _user_id) THEN
    RETURN true;
  END IF;
  IF g.kind = 'everyone' THEN RETURN true; END IF;
  IF g.kind = 'admins' THEN
    RETURN public.has_role(_user_id, 'admin'::public.app_role);
  END IF;
  IF g.kind = 'committee' THEN
    RETURN public.has_role(_user_id, 'committee'::public.app_role);
  END IF;
  IF g.kind = 'course_owners' THEN
    RETURN EXISTS (SELECT 1 FROM public.user_courses uc
                   WHERE uc.user_id = _user_id AND uc.course_id = g.course_id);
  END IF;
  IF g.kind = 'package_owners' THEN
    RETURN EXISTS (SELECT 1 FROM public.package_purchases pp
                   WHERE pp.user_id = _user_id AND pp.package_id = g.package_id);
  END IF;
  IF g.kind = 'no_course' THEN
    RETURN NOT EXISTS (SELECT 1 FROM public.user_courses uc WHERE uc.user_id = _user_id);
  END IF;
  RETURN false;
END; $$;

CREATE OR REPLACE FUNCTION public.my_announcements()
RETURNS SETOF public.site_announcements
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT a.* FROM public.site_announcements a
  WHERE NOT EXISTS (SELECT 1 FROM public.announcement_audiences aa WHERE aa.announcement_id = a.id)
     OR EXISTS (
       SELECT 1 FROM public.announcement_audiences aa
       WHERE aa.announcement_id = a.id
         AND public.user_in_group(auth.uid(), aa.group_id)
     )
  ORDER BY a.sort ASC, a.created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.my_announcements() TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_list_group_members(_group_id uuid)
RETURNS TABLE(user_id uuid, username text, full_name text, email text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  RETURN QUERY
  SELECT u.id,
    COALESCE(p.username, u.raw_user_meta_data->>'username', split_part(u.email::text,'@',1)),
    COALESCE(p.full_name, u.raw_user_meta_data->>'full_name', ''),
    COALESCE(p.email, u.email::text)
  FROM public.user_group_members m
  JOIN auth.users u ON u.id = m.user_id
  LEFT JOIN public.profiles p ON p.id = m.user_id
  WHERE m.group_id = _group_id
  ORDER BY 2;
END; $$;

CREATE OR REPLACE FUNCTION public.admin_group_counts()
RETURNS TABLE(group_id uuid, member_count bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  RETURN QUERY
  SELECT g.id,
    (SELECT count(*) FROM auth.users u WHERE public.user_in_group(u.id, g.id))::bigint
  FROM public.user_groups g;
END; $$;

REVOKE EXECUTE ON FUNCTION public.user_in_group(uuid, uuid) FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_server_stats()
RETURNS jsonb
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'storage'
AS $$
DECLARE
  result jsonb;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  SELECT jsonb_build_object(
    'db_size_bytes', pg_database_size(current_database()),
    'generated_at', now(),
    'buckets', COALESCE((
      SELECT jsonb_agg(b ORDER BY (b->>'bytes')::bigint DESC) FROM (
        SELECT jsonb_build_object(
          'bucket', o.bucket_id,
          'files', count(*),
          'bytes', COALESCE(sum(COALESCE((o.metadata->>'size')::bigint, 0)), 0),
          'largest_bytes', COALESCE(max(COALESCE((o.metadata->>'size')::bigint, 0)), 0),
          'last_upload', max(o.created_at)
        ) AS b
        FROM storage.objects o
        GROUP BY o.bucket_id
      ) s
    ), '[]'::jsonb),
    'growth', jsonb_build_object(
      'bytes_30d', COALESCE((SELECT sum(COALESCE((metadata->>'size')::bigint,0)) FROM storage.objects WHERE created_at >= now() - interval '30 days'), 0),
      'bytes_90d', COALESCE((SELECT sum(COALESCE((metadata->>'size')::bigint,0)) FROM storage.objects WHERE created_at >= now() - interval '90 days'), 0),
      'files_30d', (SELECT count(*) FROM storage.objects WHERE created_at >= now() - interval '30 days')
    ),
    'largest_files', COALESCE((
      SELECT jsonb_agg(f) FROM (
        SELECT jsonb_build_object(
          'bucket', o.bucket_id,
          'name', o.name,
          'bytes', COALESCE((o.metadata->>'size')::bigint, 0),
          'created_at', o.created_at
        ) AS f
        FROM storage.objects o
        ORDER BY COALESCE((o.metadata->>'size')::bigint, 0) DESC
        LIMIT 25
      ) s2
    ), '[]'::jsonb),
    'tables', COALESCE((
      SELECT jsonb_agg(t) FROM (
        SELECT jsonb_build_object(
          'name', c.relname,
          'bytes', pg_total_relation_size(c.oid),
          'rows', GREATEST(c.reltuples::bigint, 0)
        ) AS t
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind = 'r'
        ORDER BY pg_total_relation_size(c.oid) DESC
        LIMIT 15
      ) s3
    ), '[]'::jsonb),
    'content', jsonb_build_object(
      'courses', (SELECT count(*) FROM public.courses),
      'subjects', (SELECT count(*) FROM public.subjects),
      'questions', (SELECT count(*) FROM public.questions),
      'lectures', (SELECT count(*) FROM public.lecture_items),
      'committee_resources', (SELECT count(*) FROM public.committee_resources),
      'users', (SELECT count(*) FROM public.profiles),
      'active_sessions', (SELECT count(*) FROM public.user_sessions WHERE last_seen_at >= now() - interval '5 minutes')
    )
  ) INTO result;
  RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION public.admin_server_stats() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_server_stats() TO authenticated;

ALTER TABLE public.profiles ALTER COLUMN device_limit DROP NOT NULL;
ALTER TABLE public.profiles ALTER COLUMN device_limit DROP DEFAULT;
UPDATE public.profiles SET device_limit = NULL WHERE device_limit = 2;