-- Rita v3 is deliberately isolated from the legacy/economic-v2 tables so an
-- incomplete experiment cannot silently change the production voice path.
create table if not exists public.rita_v3_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'starting' check (status in ('starting','connected','ended','failed')),
  personality text not null default 'kind',
  language_preference text not null default 'automatic',
  dialect_preference text not null default 'ar-JO',
  provider_session_id text,
  model_proof jsonb not null default '{}'::jsonb,
  error_code text,
  started_at timestamptz not null default now(),
  connected_at timestamptz,
  ended_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists rita_v3_sessions_user_started_idx
  on public.rita_v3_sessions(user_id, started_at desc);
create unique index if not exists rita_v3_provider_session_idx
  on public.rita_v3_sessions(provider_session_id) where provider_session_id is not null;

create table if not exists public.rita_v3_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.rita_v3_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  value_ms integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists rita_v3_events_session_created_idx
  on public.rita_v3_events(session_id, created_at);
create index if not exists rita_v3_events_name_created_idx
  on public.rita_v3_events(event_name, created_at desc);

create table if not exists public.rita_v3_learning_staging (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.rita_v3_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  intent text not null check (intent in ('translation','word_meaning','language_word_list','explicit_save')),
  items jsonb not null default '[]'::jsonb,
  destination jsonb not null default '{}'::jsonb,
  saved_at timestamptz,
  undone_at timestamptz,
  expires_at timestamptz not null default (now() + interval '6 hours'),
  created_at timestamptz not null default now()
);

alter table public.rita_v3_sessions enable row level security;
alter table public.rita_v3_events enable row level security;
alter table public.rita_v3_learning_staging enable row level security;

drop policy if exists "users read own rita v3 sessions" on public.rita_v3_sessions;
create policy "users read own rita v3 sessions" on public.rita_v3_sessions
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists "users read own rita v3 events" on public.rita_v3_events;
create policy "users read own rita v3 events" on public.rita_v3_events
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists "users manage own rita v3 learning" on public.rita_v3_learning_staging;
create policy "users manage own rita v3 learning" on public.rita_v3_learning_staging
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select on public.rita_v3_sessions, public.rita_v3_events to authenticated;
grant select, insert, update, delete on public.rita_v3_learning_staging to authenticated;
grant all on public.rita_v3_sessions, public.rita_v3_events, public.rita_v3_learning_staging to service_role;
grant usage, select on sequence public.rita_v3_events_id_seq to service_role;
